can_driver_node:
  control_frequency: 100.0
  debug_bypass_ros_control: false
  motor_query_hz: 20.0
  startup_position_sync_timeout_sec: 1.0
  safety_stop_on_fault: true
  safety_require_enabled_for_motion: true
  max_position_step_rad: 0.0
  safety_hold_after_device_recover: true
  init_loopback: false

  joints:
    - name: left_front_wheel_joint
      motor_id: 0x01
      protocol: DM
      can_device: can0
      control_mode: velocity
      direction_sign: 1.0

    - name: right_front_wheel_joint
      motor_id: 0x02
      protocol: DM
      can_device: can0
      control_mode: velocity
      direction_sign: -1.0
